USE [master]
GO

CREATE DATABASE [MangoJRLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MangoJRLibrary', FILENAME = N'C:\SQL Server Training\MSSQL16.MSSQLSERVER\MSSQL\DATA\MangoJRLibrary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
 LOG ON 
( NAME = N'MangoJRLibrary_log', FILENAME = N'C:\SQL Server Training\MSSQL16.MSSQLSERVER\MSSQL\DATA\MangoJRLibrary_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 131072KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MangoJRLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MangoJRLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MangoJRLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MangoJRLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MangoJRLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MangoJRLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET RECOVERY FULL 
GO

ALTER DATABASE [MangoJRLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [MangoJRLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MangoJRLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MangoJRLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MangoJRLibrary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MangoJRLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MangoJRLibrary] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MangoJRLibrary] SET QUERY_STORE = ON
GO

ALTER DATABASE [MangoJRLibrary] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MangoJRLibrary] SET  READ_WRITE 
GO


